### PR TITLE
chore: Update CODEOWNERS

### PR DESCRIPTION
**Pull request by TimePrinciple**
### Summary of the PR

Add @TimePrinciple to maintain RISC-V part.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
Hey @TimePrinciple, did you check the guidelines for becoming a maintainer? Here they are: https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer. While you did contribute the RISC-V code, I think you have not been active in the repository besides that. This is from the guidelines of becoming a maintainer:
"first ramp up on the repositories by going through the documentation, looking at issues, review and submit pull requests."

Since you are not proposed as a maintainer by an existing rust-vmm gatekeeper or maintainer, I would personally like to see more activity on the project before promoting you this role. It would also be preferably for a maintainer to propose you, and you opening the PR to add yourself as an owner once a proposal was made.

@roypat @stefano-garzarella you've been more active on @TimePrinciple PRs. Could you also comment on this topic?

Thanks!

**Comment by TimePrinciple** [comment]
> Hey @TimePrinciple, did you check the guidelines for becoming a maintainer? Here they are: https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer. While you did contribute the RISC-V code, I think you have not been active in the repository besides that. This is from the guidelines of becoming a maintainer: "first ramp up on the repositories by going through the documentation, looking at issues, review and submit pull requests."
> 
> Since you are not proposed as a maintainer by an existing rust-vmm gatekeeper or maintainer, I would personally like to see more activity on the project before promoting you this role. It would also be preferably for a maintainer to propose you, and you opening the PR to add yourself as an owner once a proposal was made.
> 
> @roypat @stefano-garzarella you've been more active on @TimePrinciple PRs. Could you also comment on this topic?
> 
> Thanks!

Thanks for replying, I will work on solving the issues and help reviewing pending PRs in this repo then. Sorry about missing these guidelines :)

**Comment by stefano-garzarella** [comment]
@andreeaflorescu I see your point!
@TimePrinciple has done a very good job in the last few months in several rust-vmm repos to enable risc-v, so I'm quite confident that he can help a lot in maintaining several repos.

Having said that, I agree that it is better to wait a while, especially to let you practice with reviews, releases, etc. At that point I will be happy to propose you as codeowner of this repo and others where you are contributing!

**Comment by andreeaflorescu** [comment]
Thanks for your input @stefano-garzarella. I will close this PR for now, thanks!

**Pull request closed without merging**
